### PR TITLE
footer added

### PR DESCRIPTION
**Pull request by geetika001**
@Ashish-khanagwal I have added the footer.It looks like this as of now:
image

Please let me know if you want any further changes or want to add something,i'll do it.
Do accept my PR
Issue #9

### CODE REVIEW

**Comment by Ashish-khanagwal** [comment]
It looks good :+1: 
Just requires one change can you please use linear gradient for the background same as used in the hero section?

**Comment by geetika001** [comment]
> It looks good 👍 Just requires one change can you please use linear gradient for the background same as used in the hero section?
image
I have changed the background.please check now

**Comment by Ashish-khanagwal** [comment]
there is some issue with social handle icons, not visible

**Comment by geetika001** [comment]
Resolved.Please check now.
image

**Review by Ashish-khanagwal — APPROVED** [review]
Code looks good to me :+1: 

Thank you for your valuable contribution.

**Pull request merged**
