### PR TITLE
Adding Loan Calculator

### PR DESCRIPTION
**Pull request by Drishti-jain21**
I have added a loan calculator project using HTML, CSS, JavaScript 
I have also added the project on the main website

### CODE REVIEW

**Comment by Ashish-khanagwal** [comment]
can you please share the ss

**Comment by Ashish-khanagwal** [comment]
@Drishti-jain21 you have to sync and fetch the upstream branch, as your branch have conflicts

**Comment by Drishti-jain21** [comment]
image

Here is the screenshot

**Comment by Ashish-khanagwal** [comment]
Thank you for your valuable contribution :+1:

**Pull request merged**
